#!/usr/bin/env python3
"""Regenerate packages/dec/golden.json from an INDEPENDENT reference.

    python3 packages/dec/scripts/gen-golden.py

WHY THIS IS NOT WRITTEN IN TYPESCRIPT.

The fixture this replaces was generated by importing `packages/dec/src/dec.ts`
and writing down whatever it returned, which made `golden.test.ts` an assertion
that dec equals dec. It could detect a CHANGE in dec; it could not detect dec
being WRONG. Proven: mutating `rescale` to `quotient + 1n` — half-up toward
+infinity instead of away from zero, the classic money bug the module's own
header claims to prevent — and regenerating with the old command left 675 of
675 rows green.

So every `expected` below is computed by CPython's `decimal` module, a
different implementation by different authors: arbitrary-precision decimal
arithmetic with explicit rounding modes, where dec uses scale-aligned bigint
integers. `ROUND_HALF_UP` in `decimal` means ties away from zero, which is
exactly dec's documented rule.

The generator does NOT import dec, and dec must never import this. Keeping it
in Python also keeps a second promise: the fixture cannot quietly drift back
into a tautology, because there is no way to reach dec from here.

THIRD AUTHORITY. `HAND_DERIVED` below transcribes literal expected values that
a human wrote out in reference/money/backend-money.spec.ts and
reference/money/frontend-decimal.test.ts. They are cited, never imported
(BUILD-PROMPT rule 7). Generation FAILS if CPython disagrees with any of them —
if that ever fires, fix the arithmetic, never the table.
"""

from __future__ import annotations

import json
import pathlib
from decimal import Decimal, ROUND_HALF_UP, localcontext

OUT = pathlib.Path(__file__).resolve().parent.parent / "golden.json"

# Wide enough that add/sub/mul are exact for every operand below (the largest
# product has 24 significant digits) and that a non-terminating quotient like
# 10/3 carries far more digits than any quantize target can double-round on.
PRECISION = 500


def fmt(value: Decimal, scale: int) -> str:
    """Render `value` at exactly `scale` fractional digits, dec's way.

    dec never emits a negative zero: `render` takes the sign from the bigint,
    which is 0n for '-0'. `decimal` does keep one, so it is dropped here. This
    is presentation of a value CPython computed, not arithmetic.
    """
    quantized = value.quantize(Decimal(1).scaleb(-scale), rounding=ROUND_HALF_UP)
    sign, digits, _exp = quantized.as_tuple()
    body = "".join(str(d) for d in digits).rjust(scale + 1, "0")
    rendered = body if scale == 0 else f"{body[:-scale]}.{body[-scale:]}"
    negative = sign == 1 and any(digits)
    return f"-{rendered}" if negative else rendered


def binary(op: str, a: str, b: str, scale: int) -> dict:
    x, y = Decimal(a), Decimal(b)
    result = {"add": x + y, "sub": x - y, "mul": x * y}[op]
    return {"op": op, "a": a, "b": b, "scale": scale, "expected": fmt(result, scale)}


def div(a: str, n: int, scale: int) -> dict:
    return {
        "op": "div",
        "a": a,
        "n": n,
        "scale": scale,
        "expected": fmt(Decimal(a) / Decimal(n), scale),
    }


def rnd(a: str, scale: int) -> dict:
    return {"op": "round", "a": a, "scale": scale, "expected": fmt(Decimal(a), scale)}


def summation(values: list[str], scale: int) -> dict:
    """Σ round(each line) — NOT round(Σ exact), and NOT a re-rounded running total.

    reference/money/backend-money.spec.ts:85-101 calls this distinction load
    bearing: the receipt prints each line and a total equal to the lines above
    it. Each value is quantized on its own; the already-rounded values are then
    added exactly.
    """
    total = sum(
        (Decimal(v).quantize(Decimal(1).scaleb(-scale), rounding=ROUND_HALF_UP) for v in values),
        Decimal(0),
    )
    return {"op": "sum", "values": values, "scale": scale, "expected": fmt(total, scale)}


def compare(a: str, b: str) -> dict:
    x, y = Decimal(a), Decimal(b)
    return {"op": "cmp", "a": a, "b": b, "expected": -1 if x < y else (1 if x > y else 0)}


def relation(op: str, a: str, b: str) -> dict:
    """gt/gte/lt/lte. Derived from cmp in dec, so the EQUALITY boundary is what
    matters: flipping gte to a strict > left all 690 tests green once."""
    x, y = Decimal(a), Decimal(b)
    expected = {"gt": x > y, "gte": x >= y, "lt": x < y, "lte": x <= y}[op]
    return {"op": op, "a": a, "b": b, "expected": expected}


def predicate(op: str, a: str) -> dict:
    x = Decimal(a)
    return {"op": op, "a": a, "expected": x == 0 if op == "isZero" else x < 0}


# --------------------------------------------------------------------------
# Operand space. Chosen for the regions the previous fixture missed: exact
# halves at several scales, values just below a half, cross-scale pairs,
# negatives on both sides, scale-0 integers, an FX rate at scale 4, and the
# numeric(12,2) ceiling that proves the internals are not doubles.
# --------------------------------------------------------------------------
CORE = [
    "0",
    "0.00",
    "-0",
    "0.005",
    "-0.005",
    "0.0045",
    "0.01",
    "-0.01",
    "0.05",
    "0.15",
    "1.005",
    "-2.50",
    "10.00",
    "19.99",
    "-12345.67",
    "9999999999.99",
]

CROSS = ["0.5", "0.05", "1", "1.2345", "-7.5", "47.8032"]

DIVIDENDS = [
    "0.00",
    "0.005",
    "-0.005",
    "0.00450",
    "1.00",
    "3.00",
    "-1.00",
    "0.25",
    "10.00",
    "126.40",
    "47.8032",
    "-9999999999.99",
]
DIVISORS = [1, -1, 2, -2, 3, -3, 7, 8, -8, 12]

ROUNDABLE = CORE + CROSS + ["2.345", "-2.345", "2.344", "0.5", "-0.5", "1.5", "-1.5", "000012.30"]

# gt/gte/lt/lte are pure derivations of cmp, so what has to be covered is the
# EQUALITY boundary and the same value written at two scales — '1.00' vs
# '1.000' — which is where flipping gte to a strict > hides.
RELATIONAL = [
    "0",
    "0.00",
    "-0",
    "1.00",
    "1.000",
    "1.01",
    "0.99",
    "-1.00",
    "9.00",
    "10.00",
    "-0.01",
    "9999999999.99",
]

SUM_LINES = [
    [],
    ["0.00"],
    ["10944.00", "1827.00", "0.50"],
    ["1.01", "2.02", "3.03"],
    ["0.01", "0.01", "0.01"],
    ["0.005", "0.005", "-0.005"],
    ["-0.005", "0.005", "0.005"],
    ["0.005", "-0.005", "0.005"],
    ["1.00", "-0.005"],
    ["0.0045", "0.0045", "0.0045"],
    ["-0.10", "-0.20", "0.30"],
    ["9999999999.99", "0.01"],
    ["47.8032", "47.8032", "47.8032"],
    ["0.5", "0.5", "0.5", "0.5"],
    ["-1.5", "-1.5"],
]

# --------------------------------------------------------------------------
# Hand-derived rows: values a human wrote out as literals in the reference
# specs. Cited, not imported. CPython must agree with every one of them.
# --------------------------------------------------------------------------
HAND_DERIVED: list[tuple] = [
    # reference/money/backend-money.spec.ts:11-21 — canonicalisation via add(x,'0')
    ("add", "0", "0", 2, "0.00"),
    ("add", "0.0", "0", 2, "0.00"),
    ("add", "7", "0", 2, "7.00"),
    ("add", "7.5", "0", 2, "7.50"),
    ("add", "7.05", "0", 2, "7.05"),
    ("add", "-3.4", "0", 2, "-3.40"),
    ("add", "000012.30", "0", 2, "12.30"),
    # backend-money.spec.ts:35-50 — sub is exact, and the canonical float trap
    ("sub", "42.00", "1.50", 2, "40.50"),
    ("sub", "40.50", "3.60", 2, "36.90"),
    ("sub", "1.00", "1.00", 2, "0.00"),
    ("sub", "1.00", "1.01", 2, "-0.01"),
    ("sub", "0.10", "0.20", 2, "-0.10"),
    ("add", "0.10", "0.20", 2, "0.30"),
    ("sub", "0.30", "0.10", 2, "0.20"),
    # backend-money.spec.ts:54-76 — HALF-UP at scale 2, the rounding boundary
    ("mul", "36.90", "57.00", 2, "2103.30"),
    ("mul", "10.00", "0.00", 2, "0.00"),
    ("mul", "1.00", "1.00", 2, "1.00"),
    ("mul", "0.05", "0.05", 2, "0.00"),
    ("mul", "0.15", "0.15", 2, "0.02"),
    ("mul", "0.10", "0.05", 2, "0.01"),
    ("mul", "0.30", "0.15", 2, "0.05"),
    ("mul", "10.00", "-1.50", 2, "-15.00"),
    ("mul", "-0.10", "0.05", 2, "-0.01"),
    ("mul", "9999999999.99", "1.00", 2, "9999999999.99"),
    # reference/money/frontend-decimal.test.ts:5-21
    ("add", "140.00", "-5", 2, "135.00"),
    ("add", "0.10", "0.2", 2, "0.30"),
    ("sub", "1.05", "1.05", 2, "0.00"),
    ("sub", "1.00", "2.50", 2, "-1.50"),
]

HAND_DERIVED_DIV: list[tuple] = [
    # frontend-decimal.test.ts:29-48
    ("126.40", 2, 2, "63.20"),
    ("10.00", 1, 2, "10.00"),
    ("0.00", 7, 2, "0.00"),
    ("1.00", 8, 2, "0.13"),
    ("3.00", 8, 2, "0.38"),
    ("10.00", 3, 2, "3.33"),
    ("20.00", 3, 2, "6.67"),
    ("126.40", 12, 2, "10.53"),
    ("-1.00", 8, 2, "-0.13"),
    ("-10.00", 3, 2, "-3.33"),
]

HAND_DERIVED_SUM: list[tuple] = [
    # backend-money.spec.ts:80-101 — including THE LOAD-BEARING TEST
    (["1.01", "2.02", "3.03"], 2, "6.06"),
    ([], 2, "0.00"),
    (["0.01", "0.01", "0.01"], 2, "0.03"),
    # frontend-decimal.test.ts:11-14
    (["10944.00", "1827.00", "0.50"], 2, "12771.50"),
]

HAND_DERIVED_CMP: list[tuple] = [
    # backend-money.spec.ts:105-115
    ("1.00", "1.00", 0),
    ("1.01", "1.00", 1),
    ("1.00", "1.01", -1),
    ("-1.00", "0.00", -1),
    ("10.00", "9.99", 1),
    ("9.99", "10.00", -1),
    # frontend-decimal.test.ts:15-21
    ("9.00", "10.00", -1),
    ("10", "10.00", 0),
    ("-0.01", "0", -1),
]


def build() -> list[dict]:
    cases: list[dict] = []

    for op in ("add", "sub", "mul"):
        for a in CORE:
            for b in CORE:
                cases.append(binary(op, a, b, 2))
        for a in CROSS:
            for b in CROSS:
                for scale in (0, 4):
                    cases.append(binary(op, a, b, scale))

    for a in DIVIDENDS:
        for n in DIVISORS:
            for scale in (2, 4):
                cases.append(div(a, n, scale))
    for a in ("0.005", "2.50", "-2.50", "126.40"):
        for n in (1, 2, -2, 3):
            cases.append(div(a, n, 0))

    for a in ROUNDABLE:
        for scale in (0, 1, 2, 3, 4, 6):
            cases.append(rnd(a, scale))

    for values in SUM_LINES:
        for scale in (0, 2, 4):
            cases.append(summation(values, scale))

    for a in CORE:
        for b in CORE:
            cases.append(compare(a, b))

    for op in ("gt", "gte", "lt", "lte"):
        for a in RELATIONAL:
            for b in RELATIONAL:
                cases.append(relation(op, a, b))

    for op in ("isZero", "isNegative"):
        for a in ROUNDABLE:
            cases.append(predicate(op, a))

    # Hand-derived rows last, each checked against CPython before it is written.
    for op, a, b, scale, expected in HAND_DERIVED:
        case = binary(op, a, b, scale)
        assert case["expected"] == expected, f"{op}({a},{b},{scale}) -> {case['expected']} != {expected}"
        cases.append(case)
    for a, n, scale, expected in HAND_DERIVED_DIV:
        case = div(a, n, scale)
        assert case["expected"] == expected, f"div({a},{n},{scale}) -> {case['expected']} != {expected}"
        cases.append(case)
    for values, scale, expected in HAND_DERIVED_SUM:
        case = summation(values, scale)
        assert case["expected"] == expected, f"sum({values},{scale}) -> {case['expected']} != {expected}"
        cases.append(case)
    for a, b, expected in HAND_DERIVED_CMP:
        case = compare(a, b)
        assert case["expected"] == expected, f"cmp({a},{b}) -> {case['expected']} != {expected}"
        cases.append(case)

    # De-duplicate on the full case identity, preserving first-seen order.
    seen: set[str] = set()
    unique: list[dict] = []
    for case in cases:
        key = json.dumps(case, sort_keys=True)
        if key not in seen:
            seen.add(key)
            unique.append(case)
    return unique


def main() -> None:
    with localcontext() as ctx:
        ctx.prec = PRECISION
        cases = build()
    body = ",\n".join("  " + json.dumps(c, separators=(",", ":")) for c in cases)
    OUT.write_text(f"[\n{body}\n]\n")
    ops: dict[str, int] = {}
    for c in cases:
        ops[c["op"]] = ops.get(c["op"], 0) + 1
    print(f"wrote {OUT} — {len(cases)} cases {ops}")


if __name__ == "__main__":
    main()
