import { describe, it, expect } from 'vitest';
import golden from '../golden.json' with { type: 'json' };
import * as dec from './index';

/**
 * The fixture is NOT generated by this module. `scripts/gen-golden.py` computes
 * every `expected` value with CPython's `decimal` module under ROUND_HALF_UP,
 * and cross-checks a hand-authored section against the literal values a human
 * wrote out in `reference/money/backend-money.spec.ts` and
 * `reference/money/frontend-decimal.test.ts`.
 *
 * That independence is the whole point. The previous fixture was generated by
 * importing `packages/dec` itself, so its 675 rows asserted dec === dec:
 * mutating `rescale` to round toward +infinity instead of away from zero — the
 * classic money bug this module's header claims to prevent — and regenerating
 * with the plan's own command left 675/675 green. Against this fixture the same
 * mutation turns 132 rows red, and the `div` sign mutation turns 15 red where
 * the old fixture had no `div` row at all.
 */
type Binary = { op: 'add' | 'sub' | 'mul'; a: string; b: string; scale: number; expected: string };
type Div = { op: 'div'; a: string; n: number; scale: number; expected: string };
type Round = { op: 'round'; a: string; scale: number; expected: string };
type Sum = { op: 'sum'; values: string[]; scale: number; expected: string };
type Cmp = { op: 'cmp'; a: string; b: string; expected: -1 | 0 | 1 };
type Relation = { op: 'gt' | 'gte' | 'lt' | 'lte'; a: string; b: string; expected: boolean };
type Predicate = { op: 'isZero' | 'isNegative'; a: string; expected: boolean };
type Case = Binary | Div | Round | Sum | Cmp | Relation | Predicate;

const cases = golden as unknown as Case[];

const EVERY_OP: Case['op'][] = [
  'add',
  'sub',
  'mul',
  'div',
  'sum',
  'cmp',
  'round',
  'gt',
  'gte',
  'lt',
  'lte',
  'isZero',
  'isNegative',
];

function apply(c: Case): string | number | boolean {
  switch (c.op) {
    case 'add':
    case 'sub':
    case 'mul':
      return dec[c.op](c.a, c.b, c.scale);
    case 'div':
      return dec.div(c.a, c.n, c.scale);
    case 'round':
      return dec.round(c.a, c.scale);
    case 'sum':
      return dec.sum(c.values, c.scale);
    case 'cmp':
      return dec.cmp(c.a, c.b);
    case 'gt':
    case 'gte':
    case 'lt':
    case 'lte':
      return dec[c.op](c.a, c.b);
    case 'isZero':
    case 'isNegative':
      return dec[c.op](c.a);
  }
}

function title(c: Case): string {
  switch (c.op) {
    case 'add':
    case 'sub':
    case 'mul':
      return `${c.op}('${c.a}', '${c.b}', ${c.scale}) === '${c.expected}'`;
    case 'div':
      return `div('${c.a}', ${c.n}, ${c.scale}) === '${c.expected}'`;
    case 'round':
      return `round('${c.a}', ${c.scale}) === '${c.expected}'`;
    case 'sum':
      return `sum([${c.values.join(', ')}], ${c.scale}) === '${c.expected}'`;
    case 'cmp':
    case 'gt':
    case 'gte':
    case 'lt':
    case 'lte':
      return `${c.op}('${c.a}', '${c.b}') === ${String(c.expected)}`;
    case 'isZero':
    case 'isNegative':
      return `${c.op}('${c.a}') === ${String(c.expected)}`;
  }
}

const binary = (
  op: 'add' | 'sub' | 'mul',
  a: string,
  b: string,
  scale: number,
): string | undefined =>
  cases.find((c): c is Binary => c.op === op && c.a === a && c.b === b && c.scale === scale)
    ?.expected;

const scaleOf = (v: string): number => {
  const dot = v.indexOf('.');
  return dot === -1 ? 0 : v.length - dot - 1;
};

describe('golden parity fixture', () => {
  it('has at least 200 cases so the backend money module can be asserted against it later', () => {
    expect(cases.length).toBeGreaterThanOrEqual(200);
  });

  it('covers every exported operation, not just add/sub/mul', () => {
    const ops = new Set(cases.map((c) => c.op));
    expect(EVERY_OP.filter((op) => !ops.has(op))).toEqual([]);
    expect(ops.size).toBe(EVERY_OP.length);
  });

  it('covers scales other than 2, negative values and cross-scale operands', () => {
    const scaled = cases.filter((c): c is Binary | Div | Round | Sum => 'scale' in c);
    const scales = [...new Set(scaled.map((c) => c.scale))].sort((x, y) => x - y);
    expect(scales.length).toBeGreaterThanOrEqual(4);
    expect(scales).toContain(0);
    expect(scales).toContain(4);
    expect(cases.some((c) => 'a' in c && c.a.startsWith('-'))).toBe(true);
    expect(cases.some((c) => String(c.expected).startsWith('-'))).toBe(true);
    // operands whose own scales differ from each other and from the target
    expect(cases.some((c) => 'b' in c && scaleOf(c.a) !== scaleOf(c.b))).toBe(true);
    // a divisor on both sides of zero, which is where div's sign XOR lives.
    // Math.sign rather than `c.n < 0`: agency/no-decimal-comparison is
    // syntactic and cannot tell this integer count from a decimal string, and
    // the rule is right to stay on in this file.
    expect(cases.some((c) => c.op === 'div' && Math.sign(c.n) === -1)).toBe(true);
  });

  /**
   * The exact-half cases `reference/money/backend-money.spec.ts:53-76` singles
   * out as the rounding boundary. The previous fixture contained not one of
   * them, which is how a mutant that rounds ties the wrong way survived it.
   */
  it('contains the half-up boundary cases the reference spec calls load-bearing', () => {
    expect(binary('mul', '0.10', '0.05', 2)).toBe('0.01');
    expect(binary('mul', '0.30', '0.15', 2)).toBe('0.05');
    expect(binary('mul', '-0.10', '0.05', 2)).toBe('-0.01');
    expect(binary('mul', '0.15', '0.15', 2)).toBe('0.02');
    expect(binary('mul', '0.05', '0.05', 2)).toBe('0.00');
    expect(binary('mul', '36.90', '57.00', 2)).toBe('2103.30');
    expect(binary('mul', '9999999999.99', '1.00', 2)).toBe('9999999999.99');
  });

  it.each(cases.map((c) => [title(c), c] as [string, Case]))('%s', (label, c) => {
    expect(apply(c), label).toBe(c.expected);
  });
});
